on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          cd server && npm install
          cd ../client && npm install

      - name: Start Server
        run: |
          cd server
          npm start & # Start the server in the background
          sleep 10   # Wait for a few seconds to ensure the server is up

      - name: Test
        run: |
          cd client
          npm run test

      - name: Deploy
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          set -e
          curl -X POST "$deploy_url"